version: '3'
services:
  nginx: 
    image: nginx:latest
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    restart: "unless-stopped"
